### ISSUE TITLE
ST7735 Plugin

### ISSUE THREAD

**Issue by ananthb** [pimoroni/pidi-plugins#5]
I'd like to implement a pipi plugin for the ST7735. Any tips or pointers before I get started?

**Comment by Gadgetoid** [comment]
You should start by copying the ST7789 plugin - https://github.com/pimoroni/pidi-plugins/blob/master/pidi-display-st7789/pidi_display_st7789/__init__.py

Then the ST7789 init and image display code should just be swapped with ST7735. 

With our ST7735 Python library ( https://github.com/pimoroni/st7735-python/ ) it should almost be a straight swap of the device name.

**Comment by ananthb** [comment]
@Gadgetoid that's exactly what I was thinking.
